name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Ruff
        run: pip install -r requirements.txt requirements-dev.txt

      - name: Ruff check
        run: ruff check . --output-format=github

